resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5   # ???? ??
        wait-duration: 1000

        retryExceptions:   # ? ??? retry? ??
          - com.example.resil4jex.exception.RetryException   # RetryException? ??? ??? ??? ??
        ignoreExceptions:
          - com.example.resil4jex.exception.IgnoreException    # IgnoreException? ??? ??? ??? x
    instances:
      retryConfig:  # config ????? ?? ?
        base-config: default
